/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WtRouteImport } from './routes/wt'
import { Route as MwRouteImport } from './routes/mw'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotesIndexRouteImport } from './routes/notes.index'
import { Route as ListsIndexRouteImport } from './routes/lists.index'
import { Route as GemsIndexRouteImport } from './routes/gems.index'
import { Route as NotesNoteIdRouteImport } from './routes/notes.$noteId'
import { Route as ListsNoteIdRouteImport } from './routes/lists.$noteId'
import { Route as GemsBibleParamIndexRouteImport } from './routes/gems.$bibleParam.index'
import { Route as GemsBibleParamNewRouteImport } from './routes/gems.$bibleParam.new'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'

const WtRoute = WtRouteImport.update({
  id: '/wt',
  path: '/wt',
  getParentRoute: () => rootRouteImport,
} as any)
const MwRoute = MwRouteImport.update({
  id: '/mw',
  path: '/mw',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIndexRoute = ListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => rootRouteImport,
} as any)
const GemsIndexRoute = GemsIndexRouteImport.update({
  id: '/gems/',
  path: '/gems/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsNoteIdRoute = ListsNoteIdRouteImport.update({
  id: '/lists/$noteId',
  path: '/lists/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const GemsBibleParamIndexRoute = GemsBibleParamIndexRouteImport.update({
  id: '/gems/$bibleParam/',
  path: '/gems/$bibleParam/',
  getParentRoute: () => rootRouteImport,
} as any)
const GemsBibleParamNewRoute = GemsBibleParamNewRouteImport.update({
  id: '/gems/$bibleParam/new',
  path: '/gems/$bibleParam/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mw': typeof MwRoute
  '/wt': typeof WtRoute
  '/lists/$noteId': typeof ListsNoteIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/gems/': typeof GemsIndexRoute
  '/lists/': typeof ListsIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/gems/$bibleParam/new': typeof GemsBibleParamNewRoute
  '/gems/$bibleParam/': typeof GemsBibleParamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mw': typeof MwRoute
  '/wt': typeof WtRoute
  '/lists/$noteId': typeof ListsNoteIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/gems': typeof GemsIndexRoute
  '/lists': typeof ListsIndexRoute
  '/notes': typeof NotesIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/gems/$bibleParam/new': typeof GemsBibleParamNewRoute
  '/gems/$bibleParam': typeof GemsBibleParamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mw': typeof MwRoute
  '/wt': typeof WtRoute
  '/lists/$noteId': typeof ListsNoteIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/gems/': typeof GemsIndexRoute
  '/lists/': typeof ListsIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/gems/$bibleParam/new': typeof GemsBibleParamNewRoute
  '/gems/$bibleParam/': typeof GemsBibleParamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mw'
    | '/wt'
    | '/lists/$noteId'
    | '/notes/$noteId'
    | '/gems/'
    | '/lists/'
    | '/notes/'
    | '/api/trpc/$'
    | '/gems/$bibleParam/new'
    | '/gems/$bibleParam/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mw'
    | '/wt'
    | '/lists/$noteId'
    | '/notes/$noteId'
    | '/gems'
    | '/lists'
    | '/notes'
    | '/api/trpc/$'
    | '/gems/$bibleParam/new'
    | '/gems/$bibleParam'
  id:
    | '__root__'
    | '/'
    | '/mw'
    | '/wt'
    | '/lists/$noteId'
    | '/notes/$noteId'
    | '/gems/'
    | '/lists/'
    | '/notes/'
    | '/api/trpc/$'
    | '/gems/$bibleParam/new'
    | '/gems/$bibleParam/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MwRoute: typeof MwRoute
  WtRoute: typeof WtRoute
  ListsNoteIdRoute: typeof ListsNoteIdRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  GemsIndexRoute: typeof GemsIndexRoute
  ListsIndexRoute: typeof ListsIndexRoute
  NotesIndexRoute: typeof NotesIndexRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  GemsBibleParamNewRoute: typeof GemsBibleParamNewRoute
  GemsBibleParamIndexRoute: typeof GemsBibleParamIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wt': {
      id: '/wt'
      path: '/wt'
      fullPath: '/wt'
      preLoaderRoute: typeof WtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mw': {
      id: '/mw'
      path: '/mw'
      fullPath: '/mw'
      preLoaderRoute: typeof MwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/': {
      id: '/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof ListsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gems/': {
      id: '/gems/'
      path: '/gems'
      fullPath: '/gems/'
      preLoaderRoute: typeof GemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/$noteId': {
      id: '/lists/$noteId'
      path: '/lists/$noteId'
      fullPath: '/lists/$noteId'
      preLoaderRoute: typeof ListsNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gems/$bibleParam/': {
      id: '/gems/$bibleParam/'
      path: '/gems/$bibleParam'
      fullPath: '/gems/$bibleParam/'
      preLoaderRoute: typeof GemsBibleParamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gems/$bibleParam/new': {
      id: '/gems/$bibleParam/new'
      path: '/gems/$bibleParam/new'
      fullPath: '/gems/$bibleParam/new'
      preLoaderRoute: typeof GemsBibleParamNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MwRoute: MwRoute,
  WtRoute: WtRoute,
  ListsNoteIdRoute: ListsNoteIdRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
  GemsIndexRoute: GemsIndexRoute,
  ListsIndexRoute: ListsIndexRoute,
  NotesIndexRoute: NotesIndexRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  GemsBibleParamNewRoute: GemsBibleParamNewRoute,
  GemsBibleParamIndexRoute: GemsBibleParamIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
